#!/bin/busybox sh

# Mount essential virtual filesystems
mkdir /proc /sys
mount -t proc none /proc
mount -t sysfs none /sys

echo -e "\n\n#####  Welcome to your custom kernel! #####\n"

# Drop to a shell
exec /bin/sh
